apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "app-server.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 5
  {{- if .Values.server.replicaCount }}
  replicas: {{ .Values.server.replicaCount }}
  {{- end }}
  {{- with .Values.server.deploymentStrategy }}
  strategy:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  minReadySeconds: {{ .Values.server.minReadySeconds | default 30 }}
  selector:
    matchLabels:
  {{- include "app-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "app-server.selectorLabels" . | nindent 8 }}
      {{- with .Values.server.annotations }}
      annotations:
    {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.server.terminationGracePeriodSeconds | default "90" }}
      {{- with .Values.server.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
      {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
        {{- toYaml .Values.server.securityContext | nindent 10 }}
        image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
        imagePullPolicy: {{ .Values.server.image.pullPolicy }}
        {{- with .Values.server.args }}
        args:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        env:
          - name: ELASTIC_APM_ENVIRONMENT
            value: {{ .Values.environment.apm }}
          - name: ELASTIC_APM_SERVICE_NAME
            value: {{ .Values.fullnameOverride }}
          - name: LOG_LEVEL
            value: {{ .Values.environment.log_level }}
        {{- with .Values.server.env }}
        {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.server.env_extra }}
        {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.server.ports }}
        ports:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.server.livenessProbe }}
        livenessProbe:
        {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.server.readinessProbe }}
        readinessProbe:
        {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.server.startupProbe }}
        startupProbe:
        {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
        {{- toYaml .Values.server.resources | nindent 10 }}
        {{- with .Values.server.volumeMounts }}
        volumeMounts:
        {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.server.lifecycle }}
        lifecycle:
        {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.volumes }}
      volumes:
      {{- toYaml . | nindent 8 }}
      {{- end }}